---
- hosts: all
  gather_facts: yes

  vars:
    working_dir: "/home/vagrant"
    app_jar_location: "{{ working_dir }}/spray-play-assembly-0.1.jar"

  pre_tasks:
    - name: update cache if needed
      apt: update_cache=yes cache_valid_time=3600

  tasks:
    - name: Ensure java is installed
      apt: name=openjdk-7-jdk state=present

    - name: Copy app over to server
      copy: src=../target/scala-2.11/spray-play-assembly-0.1.jar dest="{{ app_jar_location }}"

    - name: Create startup script
      template: src=templates/startup.j2  dest="{{ working_dir }}/startup.sh" mode=777

    - name: Start the server
      command: "sh {{ working_dir }}/startup.sh"